### PR TITLE
fix actions in brackets not working

### PR DESCRIPTION
**Pull request by patricklx**

### CODE REVIEW

**Comment by machty** [comment]
@bantic @mixonic how does this look to yall?

**Comment by bantic** [comment]
@patricklx Can you provide an integration test of the emblem syntax itself?
Adding a test after these [other bracketed attr tests](https://github.com/machty/emblem.js/blob/master/tests/integration/mustaches-test.js#L328-L346) would be helpful.

Is this intended to fix #232?

**Comment by patricklx** [comment]
okay, i'm on it. yes it's indented to fix that.

**Comment by patricklx** [comment]
done

**Comment by bantic** [comment]
thank you!

**Pull request merged**
