### PR TITLE
0.5.0 beta

### PR DESCRIPTION
**Pull request by mixonic**
This branch will merge into master, then become 0.5.0.

Please see https://github.com/machty/emblem.js/pull/196 for context. The 0.5.0 release will dramatically change the way Emblem works- it will change from a Handlebars AST-compatible compiler into a template printer.

* This release will break support for "vanilla" Handlebars. See [VANILLA_HANDLEBARS.md](https://github.com/machty/emblem.js/blob/0.5.0-beta/VANILLA_HANDLEBARS.md) for ideas on how we can re-introduce this with a later release.
* Ember-CLI apps should use 0.5.0 with the [ember-cli-emblem-hbs-printer](https://github.com/201-created/ember-cli-emblem-hbs-printer) addon. A 0.1.0 version will be released after Emblem is released.
* This branch will need a manual merge. The diff is so large that rebase gets confused about how the files should be renamed. A merge should go smoothly though.

### CODE REVIEW

**Comment by mixonic** [comment]
All issues on the [0.5.0 milestone](https://github.com/machty/emblem.js/milestones/0.5.0) are closed. This is ready to merge @machty!

**Comment by mixonic** [comment]
Whoops, I lied. Adding two issues now.

**Comment by mixonic** [comment]
Merged! Woo!

**Comment by coladarci** [comment]
:+1:  :+1:

**Comment by coladarci** [comment]
Very excited to try this out - we have a huge emblem project that has a brutally slow template.. 
With this gemfile:
```
gem 'ember-rails', '0.16.1'
gem 'ember-source', '1.10.0'
gem 'emblem-rails', '0.2.1'
gem 'emblem-source', github: 'machty/emblem.js',     branch: 'master'
gem 'barber-emblem', github: 'machty/barber-emblem', branch: 'master'
```
When I recompile assets, I get this error:
```
Compiler said: ReferenceError: Can't find variable: Handlebars
```
Looks like someone, somewhere, isn't using HTMLBars and I don't have the background to really understand where to start looking. Any help?

Really really appreciate this re-write...

**Comment by bantic** [comment]
@coladarci I believe we'll need some additional work to update the emblem-source gem as well. We're tracking this in #216

**Comment by coladarci** [comment]
Thanks @bantic - exciting stuff.....

**Comment by josemarluedke** [comment]
Awesome work guys! Very exited!!! Thanks for your hard work.

**Pull request merged**
